sudo: required
services:
  - docker

before_install:
  - docker build . -t thainam83vn/eazy_bi_client -f Dockerfile.dev

script:
  - docker run thainam83vn/eazy_bi_client npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: 'docker'
  env: 'Docker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-793085127332'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET'
